In [3]:
import pandas as pd

df = pd.read_csv('survey.csv')

In [4]:
columns_with_unknown = df.isin(['Unknown']).any()

# Get the names of columns containing 'UNKNOWN'
columns_with_unknown_names = columns_with_unknown[columns_with_unknown].index.tolist()

# Count the number of columns containing 'UNKNOWN'
num_columns_with_unknown = len(columns_with_unknown_names)

# Print the results
print(f"Number of columns containing 'Unknown': {num_columns_with_unknown}")
print("Columns with 'Unknown':")
for col in columns_with_unknown_names:
    print(col)

Number of columns containing 'Unknown': 4
Columns with 'Unknown':
state
self_employed
work_interfere
comments

In [5]:
df.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,Unknown,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,Unknown
1,2014-08-27 11:29:37,44,M,United States,IN,Unknown,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,Unknown
2,2014-08-27 11:29:44,32,Male,Canada,Unknown,Unknown,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,Unknown
3,2014-08-27 11:29:46,31,Male,United Kingdom,Unknown,Unknown,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,Unknown
4,2014-08-27 11:30:22,31,Male,United States,TX,Unknown,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,Unknown

In [6]:
from Mental_Health.utils.main_utils import read_yaml_file
schema_config = read_yaml_file(file_path=r'../config/schema.yaml')

In [7]:
data_null_handler=schema_config

In [8]:
# Replace 'UNKNOWN' with the specified values from the YAML file
def replace_unknown_values(df: pd.DataFrame, data_null_handler: dict) -> pd.DataFrame:
    for column, replacement in data_null_handler['data_null_handler'].items():
        if column in df.columns:
            df[column] = df[column].replace('Unknown', replacement[0])
    return df

In [9]:
# Apply the function to the DataFrame
df = replace_unknown_values(df, data_null_handler)

In [10]:
df.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,Yes,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,Unknown
1,2014-08-27 11:29:37,44,M,United States,IN,Yes,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,Unknown
2,2014-08-27 11:29:44,32,Male,Canada,Unknown,Yes,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,Unknown
3,2014-08-27 11:29:46,31,Male,United Kingdom,Unknown,Yes,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,Unknown
4,2014-08-27 11:30:22,31,Male,United States,TX,Yes,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,Unknown

In [11]:
columns_with_unknown = df.isin(['Unknown']).any()

# Get the names of columns containing 'UNKNOWN'
columns_with_unknown_names = columns_with_unknown[columns_with_unknown].index.tolist()

# Count the number of columns containing 'UNKNOWN'
num_columns_with_unknown = len(columns_with_unknown_names)

# Print the results
print(f"Number of columns containing 'Unknown': {num_columns_with_unknown}")
print("Columns with 'Unknown':")
for col in columns_with_unknown_names:
    print(col)

Number of columns containing 'Unknown': 2
Columns with 'Unknown':
state
comments

In [12]:
df

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,Yes,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,Unknown
1,2014-08-27 11:29:37,44,M,United States,IN,Yes,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,Unknown
2,2014-08-27 11:29:44,32,Male,Canada,Unknown,Yes,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,Unknown
3,2014-08-27 11:29:46,31,Male,United Kingdom,Unknown,Yes,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,Unknown
4,2014-08-27 11:30:22,31,Male,United States,TX,Yes,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2015-09-12 11:17:21,26,male,United Kingdom,Unknown,No,No,Yes,Don't know,26-100,...,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,Unknown
1255,2015-09-26 01:07:35,32,Male,United States,IL,No,Yes,Yes,Often,26-100,...,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,Unknown
1256,2015-11-07 12:36:58,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,...,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,Unknown
1257,2015-11-30 21:25:06,46,f,United States,NC,No,No,No,Don't know,100-500,...,Don't know,Yes,No,No,No,No,No,No,No,Unknown
1258,2016-02-01 23:04:31,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,...,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,Unknown

In [13]:
from Mental_Health.entity.estimator import TargetValueMapping

target_feature=df['treatment']
target_feature_train_df = target_feature.replace(
                    TargetValueMapping()._asdict()
                )
target_feature_train_df

C:\Users\Sumai\AppData\Local\Temp\ipykernel_2136\1152087423.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  target_feature_train_df = target_feature.replace(

0       0
1       1
2       1
3       0
4       1
       ..
1254    0
1255    0
1256    0
1257    1
1258    0
Name: treatment, Length: 1259, dtype: int64

In [ ]:
TargetValueMapping()._asdict()